excluded:
  - Generated/Strings.swift
  - FakeNFTUITests/


disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - blanket_disable_command
  - line_length
